apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

# Kustomize will specifically look for this image and update its tag
images:
- name: quangtruong452001/discord-feedback-server
  newName: quangtruong452001/discord-feedback-server
  newTag: 5f7c9f09b0aaa4282cda3e65cd544b9ac85fe1d0
- name: your-docker-username/discord-feedback-server
  newName: your-docker-username/discord-feedback-server
  newTag: latest
