apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

# Kustomize will specifically look for this image and update its tag
images:
  - name: your-docker-username/discord-feedback-server
    newName: your-docker-username/discord-feedback-server
    newTag: latest
