apiVersion: v1
kind: Secret
metadata:
  name: discord-feedback-server-secrets
type: Opaque
data:
  MONGODB_CONNECTION_STRING: bW9uZ29kYitzcnY6Ly9xdWFuZzpxdWFuZ0BjbHVzdGVyMC5hdHZ3Y294Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIwCg==

