apiVersion: apps/v1
kind: Service
metadata:
  name: discord-feedback-server-service
spec:
  selector:
    app: discord-feedback-server-deploy
  ports:
    - protocol: TCP
      port: 3055
      targetPort: 3055
  type: NodePort
